name: parking
description: graduation project 


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.0+1
  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.0
  google_fonts: ^0.3.9
  form_field_validator: ^1.0.1
  google_maps_flutter: ^0.5.25+3
  google_sign_in: ^4.5.1
  floating_search_bar: ^0.3.0
  geolocator: ^5.3.1
  geocoder: ^0.2.1
  location: ^3.0.2
  flutter_google_places: ^0.2.5
  flutter_polyline_points: ^0.1.0
  google_maps_webservice: ^0.0.16
  http: ^0.12.1
  flutter_bloc: any
  url_launcher: any

  firebase_storage: ^3.1.5
  image_picker: ^0.6.6+1
  modal_progress_hud: ^0.1.3
  cached_network_image: ^2.1.0+1
  shared_preferences: ^0.5.7+1
  flutter_app_badger: ^1.1.2
  flutter_widgets: ^0.1.7+1
  photo_view: ^0.9.2
  font_awesome_flutter: any




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/gicon.png
    - images/marker.png
    - images/carIcon.png
    - images/erknly.jpg
    - images/contact.jpg
    - images/aboutuss.jpg
    - images/fasebook.png
    - images/twitter.png
    - images/Instagram.png
    - images/youtube.png
    - images/car.png
    - images/Caar.png
    - images/trafficjam.jpg
    - images/offerpoint.png
    - images/faq.png
    - images/google_logo.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
